// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'index',
    {
      type: 'autogenerated',
      dirName: 'architecture',
    },
    {
      type: 'category',
      label: 'Working reference material',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'referencia'},
        {type: 'autogenerated', dirName: 'metodos'},
        {type: 'autogenerated', dirName: 'catalogo'},
        {type: 'autogenerated', dirName: 'operacion'},
        {type: 'autogenerated', dirName: 'playbooks'},
        {type: 'autogenerated', dirName: 'pocket'},
      ],
    },
    {
      type: 'category',
      label: 'Historical work packets',
      collapsed: true,
      items: [
        'CODEX_PUBLISH_FIRST_POVERTY_RELEASE',
        'WORK_PACKET_REPAIR_DEPLOYMENT',
      ],
    },
  ],
};

export default sidebars;
